#include <GLES2/gl2.h>


const char* gVertexShader =
  "attribute vec4 a_position;\n"
  "attribute vec2 a_texCoord;\n"
  "varying   vec2 v_texCoord;\n"
  "void main() \n"
  "{\n"
  "  gl_Position = a_position;\n"
  "  v_texCoord  = a_texCoord;\n"
  "}\n";

const char* gFragmentShader =
  "precision mediump    float;\n"
  "varying   vec2       v_texCoord;\n"
  "uniform   sampler2D  s_texture;\n"
  "uniform   vec2       u_Resolution;\n"  // - - - Actual screen resolution (e.g., 1920x1080)
  "uniform   int        u_ShaderIndex;\n" // - - - Uniform to select shader style
  "uniform   float      u_Time;\n"        // - - - Uniform for time, used by some animated effects

  "float random(vec2 st) \n"
  "{\n"
  "  return fract(sin(dot(st.xy, vec2(12.9898,78.233))) * 43758.5453123);\n"
  "}\n"

  "void main()\n"
  "{\n"
  "  vec3   color         = texture2D(s_texture, v_texCoord).rgb;\n"
  "  vec2   corrected_uv  = v_texCoord;\n"
  "  float  dist          = 0.0;\n"
  "  vec2   pos           = -1.0 + 2.0 * v_texCoord;\n"
  "         dist          = dot(pos, pos);\n"
  "\n"
  "if (u_ShaderIndex == 1) \n"
  "{\n\n"
  "  // - - - CRT Barrel TV Shader (Curvature, prominent scanlines, vignette) - - - \n\n"
  "  // - - - 1. Curvature (Barrel Distortion)\n"
  "  corrected_uv = v_texCoord + pos * dist * 0.015;\n"
  "  corrected_uv = clamp(corrected_uv, 0.0, 1.0);\n"
  "  color        = texture2D(s_texture, corrected_uv).rgb;\n"
  "\n"
  "  // - - - 2. Scanlines - - - \n"
  "  if (mod(gl_FragCoord.y, 2.0) < 1.0)\n"
  "  {\n"
  "     color *= 0.65; // Darken by 35%\n"
  "  }\n"
  "\n"
  "  // - - - 3. Vignette\n"
  "  color *= 1.0 - dist * 0.25;\n"
  "}\n"
  "else if (u_ShaderIndex == 2)\n"
  "{\n\n"
  "  // - - - Chromatic Aberration Shader (More pronounced color shifting) - - -\n\n"
  "  // - - - 1. Curvature (Barrel Distortion) - Very subtle\n"
  "  corrected_uv = v_texCoord + pos * dist * 0.01;\n"
  "  corrected_uv = clamp(corrected_uv, 0.0, 1.0);\n"
  "\n"
  "  vec3 temp_color;\n"
  "  // - - - 2. Chromatic Aberration: Increased offset for more noticeable color shift\n"
  "  vec2 offset  = vec2(1.0 / u_Resolution.x, 1.0 / u_Resolution.y) * 6.0;\n"
  "  temp_color.r = texture2D(s_texture, corrected_uv - offset.x * vec2(1.0, 0.0)).r;\n"
  "  temp_color.g = texture2D(s_texture, corrected_uv).g;\n"
  "  temp_color.b = texture2D(s_texture, corrected_uv + offset.x * vec2(1.0, 0.0)).b;\n"
  "  color        = temp_color;\n"
  "\n"
  "  // - - - 3. Scanlines\n"
  "  if (mod(gl_FragCoord.y, 2.0) < 1.0)\n"
  "  {\n"
  "    color *= 0.6; // Darken by 40%\n"
  "  }\n"
  "\n"
  "  // - - - 4. Vignette\n"
  "  color *= 1.0 - dist * 0.2;\n"
  "}\n "
  "else if (u_ShaderIndex == 3)\n"
  "{\n\n"
  "  // - - - Bad TV Signal Shader (Noise + Wobble) - - -\n\n"
  "  // - - -1. Horizontal Wobble (subtle wave effect)\n"
  "  float wobble_strength  = 0.005;    // Adjust for more/less wobble intensity\n"
  "  float wobble_speed     = 8.0;      // Adjust for faster/slower wobble animation\n"
  "  // - - - Calculate a sine wave offset based on y-coordinate and time\n"
  "  float wobble_offset  = sin(v_texCoord.y * 15.0 + u_Time * wobble_speed) * wobble_strength;\n"
  "  corrected_uv.x       = v_texCoord.x + wobble_offset;\n"
  "  corrected_uv         = clamp(corrected_uv, 0.0, 1.0);\n"
  "  color                = texture2D(s_texture, corrected_uv).rgb;\n"
  "\n"
  "  // - - - 2. Static Noise\n"
  "  float noise_strength = 0.2; // Adjust for more/less static visibility\n"
  "  float noise = random(gl_FragCoord.xy / u_Resolution + u_Time * 0.1) * noise_strength;\n"
  "  color -= noise;\n"
  "\n"
  "  // - - - 3. Subtle Scanlines\n"
  "  if (mod(gl_FragCoord.y, 2.0) < 1.0)\n "
  "  {\n"
  "    color *= 0.9; // Slightly darken for subtle scanlines\n"
  "  }\n"
  "  // - - - 4. Very subtle vignette\n"
  "  color *= 1.0 - dist * 0.1;\n"
  "}\n"
  "else if (u_ShaderIndex == 4)\n "
  "{\n"
  "  // - - - Phosphor Decay / Ghosting Shader (New) ---\n"
  "  vec3 current_color = texture2D(s_texture, v_texCoord).rgb;\n"
  "\n"
  "// - - - 2. Sample a slightly lagged version of the image for the ghosting effect\n"
  "vec2 ghost_offset_uv = vec2(-1.0 / u_Resolution.x * 2.0, -1.0 / u_Resolution.y * 2.0);\n" // 2 pixels up-left\n"
  "vec3 ghost_color     = texture2D(s_texture, v_texCoord + ghost_offset_uv).rgb;\n"
  "\n"
  "// - - - 3. Blend the current color with the ghost color\n"
  "float  decay_factor  = 0.9; // Subtle ghosting\n"
  "       color         = mix(current_color, ghost_color, decay_factor);\n"
  "\n"
  "// - - - 4. Subtle Scanlines\n"
  "  if (mod(gl_FragCoord.y, 2.0) < 1.0)\n "
  "  {\n"
  "    color *= 0.85; // Slightly darken for subtle scanlines\n"
  "  }\n"
  "  // - - - 5. Very subtle vignette\n"
  "  color *= 1.0 - dist * 0.15;\n"
  "}\n"
  "\n"
  "// - - - Final color output\n"
  "gl_FragColor = vec4(color, 1.0);\n"
  "}\n";


int currentShaderIndex = 0;