#include "cpu.h"
#include "bus.h"
#include "cartridge.h"
#include "emu.h"
#include "../../ForgeLib/include/asserts.h"
#include "../../ForgeLib/include/logger.h"

static bool         started = false;
CPUContext   cpuCTX  = {0};
#define POSSIBLE_INSTRUCTION_COUNT 256


static Instruction instructions[POSSIBLE_INSTRUCTION_COUNT] =
{
    // - - - Hex because easy to reference here: https://meganesulli.com/static/851d34afbc4673ee915a8233fda67922/78d47/opcode-tables-screenshot.png
        [0x00] = {INSTRUCTION_NOP, ADDRESS_MODE_IMP},
        [0x01] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_D16, REG_BC},
        [0x02] = {INSTRUCTION_LOAD, ADDRESS_MODE_MR_R, REG_BC, REG_A},
        [0x03] = {INSTRUCTION_INCREMENT, ADDRESS_MODE_R, REG_BC},
        [0x04] = {INSTRUCTION_INCREMENT, ADDRESS_MODE_R, REG_B},
        [0x05] = {INSTRUCTION_DECREMENT, ADDRESS_MODE_R, REG_B},
        [0x06] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_D8, REG_B},

        [0x08] = {INSTRUCTION_LOAD, ADDRESS_MODE_A16_R, REG_NONE, REG_SP},
        [0x09] = {INSTRUCTION_ADD, ADDRESS_MODE_R_R, REG_HL, REG_BC},


        [0x0A] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_MR, REG_A, REG_BC},
        [0x0B] = {INSTRUCTION_DECREMENT, ADDRESS_MODE_R, REG_BC},
        [0x0C] = {INSTRUCTION_INCREMENT, ADDRESS_MODE_R, REG_C},
        [0x0D] = {INSTRUCTION_DECREMENT, ADDRESS_MODE_R, REG_C},

        [0x0E] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_D8, REG_C},

        //0x1X
        [0x11] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_D16, REG_DE},
        [0x12] = {INSTRUCTION_LOAD, ADDRESS_MODE_MR_R, REG_DE, REG_A},
        [0x13] = {INSTRUCTION_INCREMENT, ADDRESS_MODE_R, REG_DE},
        [0x14] = {INSTRUCTION_INCREMENT, ADDRESS_MODE_R, REG_D},
        [0x15] = {INSTRUCTION_DECREMENT, ADDRESS_MODE_R, REG_D},
        [0x16] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_D8, REG_D},
        [0x18] = {INSTRUCTION_JR, ADDRESS_MODE_D8},
        [0x19] = {INSTRUCTION_ADD, ADDRESS_MODE_R_R, REG_HL, REG_DE},
        [0x1A] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_MR, REG_A, REG_DE},
        [0x1B] = {INSTRUCTION_DECREMENT, ADDRESS_MODE_R, REG_DE},
        [0x1C] = {INSTRUCTION_INCREMENT, ADDRESS_MODE_R, REG_E},
        [0x1D] = {INSTRUCTION_DECREMENT, ADDRESS_MODE_R, REG_E},
        [0x1E] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_D8, REG_E},

        //0x2X
        [0x20] = {INSTRUCTION_JR, ADDRESS_MODE_D8, REG_NONE, REG_NONE, CONDITIONS_NZ},
        [0x21] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_D16, REG_HL},
        [0x22] = {INSTRUCTION_LOAD, ADDRESS_MODE_HLI_R, REG_HL, REG_A},
        [0x23] = {INSTRUCTION_INCREMENT, ADDRESS_MODE_R, REG_HL},
        [0x24] = {INSTRUCTION_INCREMENT, ADDRESS_MODE_R, REG_H},
        [0x25] = {INSTRUCTION_DECREMENT, ADDRESS_MODE_R, REG_H},
        [0x26] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_D8, REG_H},
        [0x28] = {INSTRUCTION_JR, ADDRESS_MODE_D8, REG_NONE, REG_NONE, CONDITIONS_Z},
        [0x29] = {INSTRUCTION_ADD, ADDRESS_MODE_R_R, REG_HL, REG_HL},
        [0x2A] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_HLI, REG_A, REG_HL},
        [0x2B] = {INSTRUCTION_DECREMENT, ADDRESS_MODE_R, REG_HL},
        [0x2C] = {INSTRUCTION_INCREMENT, ADDRESS_MODE_R, REG_L},
        [0x2D] = {INSTRUCTION_DECREMENT, ADDRESS_MODE_R, REG_L},
        [0x2E] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_D8, REG_L},

        //0x3X
        [0x30] = {INSTRUCTION_JR, ADDRESS_MODE_D8, REG_NONE, REG_NONE, CONDITIONS_NC},
        [0x31] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_D16, REG_SP},
        [0x32] = {INSTRUCTION_LOAD, ADDRESS_MODE_HLD_R, REG_HL, REG_A},
        [0x33] = {INSTRUCTION_INCREMENT, ADDRESS_MODE_R, REG_SP},
        [0x34] = {INSTRUCTION_INCREMENT, ADDRESS_MODE_MR, REG_HL},
        [0x35] = {INSTRUCTION_DECREMENT, ADDRESS_MODE_MR, REG_HL},
        [0x36] = {INSTRUCTION_LOAD, ADDRESS_MODE_MR_D8, REG_HL},
        [0x38] = {INSTRUCTION_JR, ADDRESS_MODE_D8, REG_NONE, REG_NONE, CONDITIONS_C},
        [0x39] = {INSTRUCTION_ADD, ADDRESS_MODE_R_R, REG_HL, REG_SP},
        [0x3A] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_HLD, REG_A, REG_HL},
        [0x3B] = {INSTRUCTION_DECREMENT, ADDRESS_MODE_R, REG_SP},
        [0x3C] = {INSTRUCTION_INCREMENT, ADDRESS_MODE_R, REG_A},
        [0x3D] = {INSTRUCTION_DECREMENT, ADDRESS_MODE_R, REG_A},
        [0x3E] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_D8, REG_A},

        //0x4X
        [0x40] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R, REG_B, REG_B},
        [0x41] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R, REG_B, REG_C},
        [0x42] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R, REG_B, REG_D},
        [0x43] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R, REG_B, REG_E},
        [0x44] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R, REG_B, REG_H},
        [0x45] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R, REG_B, REG_L},
        [0x46] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_MR, REG_B, REG_HL},
        [0x47] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R, REG_B, REG_A},
        [0x48] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R, REG_C, REG_B},
        [0x49] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R, REG_C, REG_C},
        [0x4A] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R, REG_C, REG_D},
        [0x4B] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R, REG_C, REG_E},
        [0x4C] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R, REG_C, REG_H},
        [0x4D] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R, REG_C, REG_L},
        [0x4E] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_MR, REG_C, REG_HL},
        [0x4F] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R, REG_C, REG_A},

        //0x5X
        [0x50] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_D, REG_B},
        [0x51] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_D, REG_C},
        [0x52] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_D, REG_D},
        [0x53] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_D, REG_E},
        [0x54] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_D, REG_H},
        [0x55] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_D, REG_L},
        [0x56] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_MR, REG_D, REG_HL},
        [0x57] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_D, REG_A},
        [0x58] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_E, REG_B},
        [0x59] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_E, REG_C},
        [0x5A] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_E, REG_D},
        [0x5B] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_E, REG_E},
        [0x5C] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_E, REG_H},
        [0x5D] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_E, REG_L},
        [0x5E] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_MR, REG_E, REG_HL},
        [0x5F] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_E, REG_A},

        //0x6X
        [0x60] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_H, REG_B},
        [0x61] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_H, REG_C},
        [0x62] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_H, REG_D},
        [0x63] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_H, REG_E},
        [0x64] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_H, REG_H},
        [0x65] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_H, REG_L},
        [0x66] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_MR, REG_H, REG_HL},
        [0x67] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_H, REG_A},
        [0x68] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_L, REG_B},
        [0x69] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_L, REG_C},
        [0x6A] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_L, REG_D},
        [0x6B] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_L, REG_E},
        [0x6C] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_L, REG_H},
        [0x6D] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_L, REG_L},
        [0x6E] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_MR, REG_L, REG_HL},
        [0x6F] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_L, REG_A},

        //0x7X
        [0x70] = {INSTRUCTION_LOAD, ADDRESS_MODE_MR_R,  REG_HL, REG_B},
        [0x71] = {INSTRUCTION_LOAD, ADDRESS_MODE_MR_R,  REG_HL, REG_C},
        [0x72] = {INSTRUCTION_LOAD, ADDRESS_MODE_MR_R,  REG_HL, REG_D},
        [0x73] = {INSTRUCTION_LOAD, ADDRESS_MODE_MR_R,  REG_HL, REG_E},
        [0x74] = {INSTRUCTION_LOAD, ADDRESS_MODE_MR_R,  REG_HL, REG_H},
        [0x75] = {INSTRUCTION_LOAD, ADDRESS_MODE_MR_R,  REG_HL, REG_L},
        [0x76] = {INSTRUCTION_HALT},
        [0x77] = {INSTRUCTION_LOAD, ADDRESS_MODE_MR_R,  REG_HL, REG_A},
        [0x78] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_A, REG_B},
        [0x79] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_A, REG_C},
        [0x7A] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_A, REG_D},
        [0x7B] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_A, REG_E},
        [0x7C] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_A, REG_H},
        [0x7D] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_A, REG_L},
        [0x7E] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_MR, REG_A, REG_HL},
        [0x7F] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_R,  REG_A, REG_A},

        //0x8X
        [0x80] = {INSTRUCTION_ADD, ADDRESS_MODE_R_R, REG_A, REG_B},
        [0x81] = {INSTRUCTION_ADD, ADDRESS_MODE_R_R, REG_A, REG_C},
        [0x82] = {INSTRUCTION_ADD, ADDRESS_MODE_R_R, REG_A, REG_D},
        [0x83] = {INSTRUCTION_ADD, ADDRESS_MODE_R_R, REG_A, REG_E},
        [0x84] = {INSTRUCTION_ADD, ADDRESS_MODE_R_R, REG_A, REG_H},
        [0x85] = {INSTRUCTION_ADD, ADDRESS_MODE_R_R, REG_A, REG_L},
        [0x86] = {INSTRUCTION_ADD, ADDRESS_MODE_MR, REG_A, REG_HL},
        [0x87] = {INSTRUCTION_ADD, ADDRESS_MODE_R_R, REG_A, REG_A},
        [0x88] = {INSTRUCTION_ADC, ADDRESS_MODE_R_R, REG_A, REG_B},
        [0x89] = {INSTRUCTION_ADC, ADDRESS_MODE_R_R, REG_A, REG_C},
        [0x8A] = {INSTRUCTION_ADC, ADDRESS_MODE_R_R, REG_A, REG_D},
        [0x8B] = {INSTRUCTION_ADC, ADDRESS_MODE_R_R, REG_A, REG_E},
        [0x8C] = {INSTRUCTION_ADC, ADDRESS_MODE_R_R, REG_A, REG_H},
        [0x8D] = {INSTRUCTION_ADC, ADDRESS_MODE_R_R, REG_A, REG_L},
        [0x8E] = {INSTRUCTION_ADC, ADDRESS_MODE_MR, REG_A, REG_HL},
        [0x8F] = {INSTRUCTION_ADC, ADDRESS_MODE_R_R, REG_A, REG_A},

        //0x9X
        [0x90] = {INSTRUCTION_SUB, ADDRESS_MODE_R_R, REG_A, REG_B},
        [0x91] = {INSTRUCTION_SUB, ADDRESS_MODE_R_R, REG_A, REG_C},
        [0x92] = {INSTRUCTION_SUB, ADDRESS_MODE_R_R, REG_A, REG_D},
        [0x93] = {INSTRUCTION_SUB, ADDRESS_MODE_R_R, REG_A, REG_E},
        [0x94] = {INSTRUCTION_SUB, ADDRESS_MODE_R_R, REG_A, REG_H},
        [0x95] = {INSTRUCTION_SUB, ADDRESS_MODE_R_R, REG_A, REG_L},
        [0x96] = {INSTRUCTION_SUB, ADDRESS_MODE_MR, REG_A, REG_HL},
        [0x97] = {INSTRUCTION_SUB, ADDRESS_MODE_R_R, REG_A, REG_A},
        [0x98] = {INSTRUCTION_SBC, ADDRESS_MODE_R_R, REG_A, REG_B},
        [0x99] = {INSTRUCTION_SBC, ADDRESS_MODE_R_R, REG_A, REG_C},
        [0x9A] = {INSTRUCTION_SBC, ADDRESS_MODE_R_R, REG_A, REG_D},
        [0x9B] = {INSTRUCTION_SBC, ADDRESS_MODE_R_R, REG_A, REG_E},
        [0x9C] = {INSTRUCTION_SBC, ADDRESS_MODE_R_R, REG_A, REG_H},
        [0x9D] = {INSTRUCTION_SBC, ADDRESS_MODE_R_R, REG_A, REG_L},
        [0x9E] = {INSTRUCTION_SBC, ADDRESS_MODE_MR, REG_A, REG_HL},
        [0x9F] = {INSTRUCTION_SBC, ADDRESS_MODE_R_R, REG_A, REG_A},

        //0xAX
        [0xAF] = {INSTRUCTION_XOR, ADDRESS_MODE_R, REG_A},

        //0xCX
        [0xC0] = {INSTRUCTION_RET, ADDRESS_MODE_IMP, REG_NONE, REG_NONE, CONDITIONS_NZ},
        [0xC1] = {INSTRUCTION_POP, ADDRESS_MODE_R, REG_BC},
        [0xC2] = {INSTRUCTION_JUMP, ADDRESS_MODE_D16, REG_NONE, REG_NONE, CONDITIONS_NZ},
        [0xC3] = {INSTRUCTION_JUMP, ADDRESS_MODE_D16},
        [0xC4] = {INSTRUCTION_CALL, ADDRESS_MODE_D16, REG_NONE, REG_NONE, CONDITIONS_NZ},
        [0xC6] = {INSTRUCTION_ADD, ADDRESS_MODE_R_A8, REG_A},
        [0xC5] = {INSTRUCTION_PUSH, ADDRESS_MODE_R, REG_BC},
        [0xC7] = {INSTRUCTION_RST, ADDRESS_MODE_IMP, REG_NONE, REG_NONE, CONDITIONS_NONE, 0x00},
        [0xC8] = {INSTRUCTION_RET, ADDRESS_MODE_IMP, REG_NONE, REG_NONE, CONDITIONS_Z},
        [0xC9] = {INSTRUCTION_RET},
        [0xCA] = {INSTRUCTION_JUMP, ADDRESS_MODE_D16, REG_NONE, REG_NONE, CONDITIONS_Z},
        [0xCC] = {INSTRUCTION_CALL, ADDRESS_MODE_D16, REG_NONE, REG_NONE, CONDITIONS_Z},
        [0xCD] = {INSTRUCTION_CALL, ADDRESS_MODE_D16},
        [0xCE] = {INSTRUCTION_ADC, ADDRESS_MODE_R_D8, REG_A},
        [0xCF] = {INSTRUCTION_RST, ADDRESS_MODE_IMP, REG_NONE, REG_NONE, CONDITIONS_NONE, 0x08},


        //0xDX
        [0xD0] = {INSTRUCTION_RET, ADDRESS_MODE_IMP, REG_NONE, REG_NONE, CONDITIONS_NC},
        [0xD1] = {INSTRUCTION_POP, ADDRESS_MODE_R , REG_DE},
        [0xD2] = {INSTRUCTION_JUMP, ADDRESS_MODE_D16, REG_NONE, REG_NONE, CONDITIONS_NC},
        [0xD4] = {INSTRUCTION_CALL, ADDRESS_MODE_D16, REG_NONE, REG_NONE, CONDITIONS_NC},
        [0xD5] = {INSTRUCTION_PUSH, ADDRESS_MODE_R, REG_DE},
        [0xD6] = {INSTRUCTION_SUB, ADDRESS_MODE_R_D8},
        [0xD7] = {INSTRUCTION_RST, ADDRESS_MODE_IMP, REG_NONE, REG_NONE, CONDITIONS_NONE, 0x10},
        [0xD8] = {INSTRUCTION_RET, ADDRESS_MODE_IMP, REG_NONE, REG_NONE, CONDITIONS_C},
        [0xD9] = {INSTRUCTION_RETI},
        [0xDA] = {INSTRUCTION_JUMP, ADDRESS_MODE_D16, REG_NONE, REG_NONE, CONDITIONS_C},
        [0xDC] = {INSTRUCTION_CALL, ADDRESS_MODE_D16, REG_NONE, REG_NONE, CONDITIONS_C},
        [0xDF] = {INSTRUCTION_RST, ADDRESS_MODE_IMP, REG_NONE, REG_NONE, CONDITIONS_NONE, 0x18},

        //0xEX
        [0xE0] = {INSTRUCTION_LDH, ADDRESS_MODE_A8_R, REG_NONE, REG_A},
        [0xE1] = {INSTRUCTION_POP, ADDRESS_MODE_R, REG_HL},
        [0xE2] = {INSTRUCTION_LOAD, ADDRESS_MODE_MR_R, REG_C, REG_A},
        [0xE5] = {INSTRUCTION_PUSH, ADDRESS_MODE_R, REG_HL},
        [0xE7] = {INSTRUCTION_RST, ADDRESS_MODE_IMP, REG_NONE, REG_NONE, CONDITIONS_NONE, 0x20},
        [0xE8] = {INSTRUCTION_ADD, ADDRESS_MODE_R_D8, REG_SP},
        [0xE9] = {INSTRUCTION_JUMP, ADDRESS_MODE_MR, REG_HL},
        [0xEA] = {INSTRUCTION_LOAD, ADDRESS_MODE_A16_R, REG_NONE, REG_A},
        [0xEF] = {INSTRUCTION_RST, ADDRESS_MODE_IMP, REG_NONE, REG_NONE, CONDITIONS_NONE, 0x28},


        //0xFX
        [0xF0] = {INSTRUCTION_LDH, ADDRESS_MODE_R_A8, REG_A},
        [0xF1] = {INSTRUCTION_POP, ADDRESS_MODE_R, REG_AF},
        [0xF2] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_MR, REG_A, REG_C},
        [0xF3] = {INSTRUCTION_DI},
        [0xF5] = {INSTRUCTION_PUSH, ADDRESS_MODE_R, REG_AF},
        [0xF7] = {INSTRUCTION_RST, ADDRESS_MODE_IMP, REG_NONE, REG_NONE, CONDITIONS_NONE, 0x30},
        [0xFA] = {INSTRUCTION_LOAD, ADDRESS_MODE_R_A16, REG_A},
        [0xFF] = {INSTRUCTION_RST, ADDRESS_MODE_IMP, REG_NONE, REG_NONE, CONDITIONS_NONE, 0x38},
};

FORGE_API Instruction* InstructionByOpcode(u8 opCode)
{
    return &instructions[opCode];
}

FORGE_API u8 cpuGetIeRegister()
{
    return cpuCTX.ieRegister;
}

FORGE_API void cpuSetIeRegister(u8 n)
{
    cpuCTX.ieRegister = n;
}

// - - - CPU IMPLEMENTATIONS


// - - - CPU HELPER FUNCTIONS

// - - - MAIN CPU FUNCTIONS
FORGE_API void cpuInit()
{
    cpuCTX.registerFile.programCounter = 0x100;
    cpuCTX.registerFile.accumulator = 0x01;
    //FORGE_ASSERT_MESSAGE(!started, "Cannot start the emulator when it is already running");
    started = true;
    FORGE_LOG_INFO("Started the emulator");
}

FORGE_API void readData(); //FETCH_DATA() EQUIVALENT IN CPU_READ

FORGE_API bool cpuTick() {
    if (!cpuCTX.halted) {
        u16 programCounter = cpuCTX.registerFile.programCounter;

        cpuCTX.currentOpcode = busRead(cpuCTX.registerFile.programCounter++);
        cpuCTX.memDest = 0;
        cpuCTX.destIsMemory = false;
        cpuCTX.currInstruction = InstructionByOpcode(cpuCTX.currentOpcode);
        readData();

        if (cpuCTX.currInstruction == NULL) {
            FORGE_LOG_FATAL("UNKNOWN INSTRUCTION AT %02X\n", cpuCTX.currInstruction);
            exit(-7);
        }
    }

    //EXECUTE
    INSTRUCTION_PROCESS process = instructionGetProcessor(cpuCTX.currInstruction->type);
    if(!process)
    {
        FORGE_LOG_DEBUG("NO PROCESS GIVEN FROM CPU");
        exit(-7);
    }
    process(&cpuCTX);
    return true;
}
